"""Literal OCR adapters, normalized evidence, and benchmark metrics."""

from .adapters import (
    Capability,
    OCRAdapter,
    OCRUnavailable,
    PaddleOCRAdapter,
    PDFTextAdapter,
    SuryaAdapter,
    TesseractAdapter,
    YomiTokuAdapter,
    capability_report,
    default_adapters,
    recognize_subset,
)
from .evaluation import (
    EvaluationReport,
    ExactCodeTokenMetric,
    GroundTruthRegion,
    OmissionAccounting,
    TextMetric,
    evaluate_ground_truth,
)
from .types import (
    Alternative,
    BBox,
    EngineEvidence,
    OCRLine,
    OCRPage,
    OCRRegion,
    OCRRequest,
    OCRSpan,
    OCRToken,
    PDFTextRun,
    make_id,
)

__all__ = [
    "Alternative",
    "BBox",
    "Capability",
    "EngineEvidence",
    "EvaluationReport",
    "ExactCodeTokenMetric",
    "GroundTruthRegion",
    "OCRAdapter",
    "OCRLine",
    "OCRPage",
    "OCRRegion",
    "OCRRequest",
    "OCRSpan",
    "OCRToken",
    "OCRUnavailable",
    "OmissionAccounting",
    "PaddleOCRAdapter",
    "PDFTextAdapter",
    "PDFTextRun",
    "SuryaAdapter",
    "TesseractAdapter",
    "TextMetric",
    "YomiTokuAdapter",
    "capability_report",
    "default_adapters",
    "evaluate_ground_truth",
    "make_id",
    "recognize_subset",
]
