"""Offline review corrections for LMDOC canonical records."""

from .patches import (
    AppliedPatch,
    CorrectionPatch,
    PatchApplication,
    PatchError,
    PatchGuard,
    PatchSchemaError,
    StalePatchError,
    UnsupportedPatchOperation,
    apply_patch,
    apply_patches,
    load_patch,
    parse_patch,
    region_fingerprint,
    text_sha256,
)
from .project import (
    REVIEW_OPERATION_STATUS,
    PageApproval,
    ReviewArtifacts,
    ReviewFinding,
    ReviewPage,
    ReviewProject,
    apply_guarded_patch_set,
    patch_set_sha256,
)

__all__ = [
    "AppliedPatch",
    "PageApproval",
    "CorrectionPatch",
    "PatchApplication",
    "PatchError",
    "PatchGuard",
    "PatchSchemaError",
    "REVIEW_OPERATION_STATUS",
    "ReviewArtifacts",
    "ReviewFinding",
    "ReviewPage",
    "ReviewProject",
    "StalePatchError",
    "UnsupportedPatchOperation",
    "apply_patch",
    "apply_guarded_patch_set",
    "apply_patches",
    "load_patch",
    "parse_patch",
    "patch_set_sha256",
    "region_fingerprint",
    "text_sha256",
]
